### ISSUE TITLE
not support redmine 3.2.1 & 3.3.0

### ISSUE THREAD

**Issue by archonwang** [kamenf/redmine_watcher_groups#12]
I used branch 
https://github.com/roma-sk3/redmine_watcher_groups

error messages
> Started GET "/watcher_groups/new?object_id=17&object_type=issue" for 192.168.60.239 at 2016-04-25 13:55:34 +0800
> Processing by WatcherGroupsController#new as JS
>   Parameters: {"object_id"=>"17", "object_type"=>"issue"}
>   Current user: hui.wang (id=8)
>   Rendered plugins/redmine_watcher_groups/app/views/watcher_groups/_new.html.erb (55.5ms)
>   Rendered plugins/redmine_watcher_groups/app/views/watcher_groups/new.js.erb (56.1ms)
> Completed 500 Internal Server Error in 66ms (ActiveRecord: 2.6ms)
> 
> ActionView::Template::Error (wrong number of arguments (1 for 0)):
>     17:   <div id="groups_for_watcher">
>     18:     <%= principals_check_box_tags 'watcher_group[group_ids][]', (
>     19:       # watched ? watched.addable_watcher_groups : 
>     20:       Group.active.all(:limit => 100)) %>
>     21:   </div>
>     22: 
>     23:   <p class="buttons">
>   plugins/redmine_watcher_groups/app/views/watcher_groups/_new.html.erb:20:in `block in _384dd777a6d7f5c6364a52d7f592dc8d'
>   plugins/redmine_watcher_groups/app/views/watcher_groups/_new.html.erb:3:in `_384dd777a6d7f5c6364a52d7f592dc8d'
>   plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
>   plugins/redmine_watcher_groups/app/views/watcher_groups/new.js.erb:1:in `_58bf33e9e32764143e2204a1f2bb3969'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by roma-sk3** [comment]
Sorry for the long answer. I solved this problem. Added support for version 3.2.1. Download and install this plug-in again from my repository

**Comment by archonwang** [comment]
Thanks, I will test it later.

**Comment by archonwang** [comment]
@roma-sk3 , Thanks. 
sorry for so long time to response, these days I updated redmine 3.2.X to 3.3.X
I will test it later.
