### ISSUE TITLE
Please tell me the license

### ISSUE THREAD

**Issue by ES0729dhun** [kamenf/redmine_watcher_groups#14]
Please tell me the license of this plug-in.

If there is no license, please tell me the following information：
1. Is this plug-in free?
2. Can I use this plug-in for commercial?

**Comment by maxrossello** [comment]
The original author @kamenf should add a license. Missing a license, default copyright law applies. So no, in theory we couldn't even fork this project.
http://choosealicense.com/no-license/

**Comment by e-evdokimov** [comment]
Good news, thanks a lot, @kamenf!
